name: Feature
description: Proposer une fonctionnalité
title: "[TEAM] "
labels: ["feature"]
body:
  - type: dropdown
    id: team
    attributes:
      label: Team
      options: [frontend, backend, ia, iot, infra, all]
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: Objectif
      description: Quel problème on résout ?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critères d’acceptation
      description: Liste claire des critères pour considérer l’issue terminée.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes / contraintes
      description: Contraintes techniques, sécurité, perf, compatibilité, etc.
